# SITE CONFIGURATION
baseurl: ""
url: "https://www.meinimalismus.de"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: meinimalismus
  favicon: assets/favicon.ico
  description: "Blog zum Thema Minimalismus und Bewusstheit:
  Ordnung im Haus, Fokus im Kopf, Konsum mit Hirn.
  Ob Reduzierung von Gedankenchaos, Unordnung oder Müll, hier gibt es allerlei
  Strategien, um unnötigen Ballast loszulassen, Prioritäten zu setzen und das
  innere und äußere Chaos zu bändigen." #used by search engines
  image: "assets/img/logo.jpg"

  # Header text
  header_text:
  header_text_feature_image: #"assets/img/xy.jpg"

  # Icons
  rss: true
  email_address: aljona.buchloh@gmail.com
  instagram: "fraulyoner"
  twitter: "fraulyoner"

  # Search feature
  search: true

  # Post navigation
  post_navigation: false

  # Related posts
  related_posts: true
  related_posts_max: 3
  related_posts_minCommon: 1

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
