# SITE CONFIGURATION
baseurl: "/meinimalismus"
url: "https://fraulyoner.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: meinimalismus
  favicon: assets/favicon.ico
  description: "Blog über Strategien und Erfahrungen im Kampf gegen das Chaos in
  Haus und Kopf: Vom Entrümpeln, Aussortieren, Ordnung schaffen und Fokus setzen." #used by search engines

  # Header text
  header_text:
  header_text_feature_image: #"assets/img/xy.jpg"

  # Icons
  rss: true
  email_address: aljona.buchloh@gmail.com
  instagram: "fraulyoner"
  twitter: "fraulyoner"

  # Search feature
  search: true

  # Localization strings
  str_follow_on: "Folge mir auf"
  str_rss_follow: "RSS Feed"
  str_email: "Kontakt aufnehmen"
  str_next_post: "Nächster Post"
  str_previous_post: "Vorheriger Post"
  str_next_page: "Ältere Posts"
  str_previous_page: "Neuere Posts"
  str_continue_reading: "Weiterlesen"
  str_search_no_results: "Keine Ergebnisse gefunden."

  # Post navigation
  post_navigation: true

  # Related posts
  related_posts: true
  related_posts_max: 4
  related_posts_minCommon: 1

# PAGINATION
paginate: 3
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
